### PR TITLE
Added UltrawideHUD and updated links.txt

### PR DESCRIPTION
**Pull request by ChristianVaughn**
Added a mod that makes the hud better sized for users with Ultrawidemonitors

### CODE REVIEW

**Comment by Clef-0** [comment]
will get to merging this shortly - sorry for delay

**Comment by Clef-0** [comment]
There's a glitch preventing this pull request from showing in my GitHub client to fix a conflict with links.txt but, regardless, I can't accept links in that file pointing to your fork of FMM-Mods for security reasons. If you're still interested in getting this on FMM (albeit a year late, sorry - I'm a bad repo maintainer) please just send me the zipped up files on Discord, or resubmit this pull request and ping me.

**Comment by Clef-0** [comment]
Additionally (and I didn't notice before), but you attempted to change _all_ the links in meta/links.txt to a different repository, not just the mods you made. I'm not sure what your intention was here, but that is unacceptable. If you want to fork or replace FMM, do so. FMM's always been under an MIT license and, regardless, it's a very simple program that could be easily improved upon / implemented better. But for FMM's default repository, there are certain standards and checks which need to be in place (checking for malicious TagTools, batch scripts, or unpermitted mods like balance changes) which I can't confirm you're doing if you were hosting files on your own repo.

**Comment by ChristianVaughn** [comment]
Sorry I didn't mean to do that. That was something I was messing around
with months after I made that pull request. Also someone told me the mod
didn't work as it was supposed to do don't worry about it. I was trying to
make it for someone but I don't own an ultra wide monitor and was trying to
help someone out. The change in links was something I was doing for a
personal thing and didn't realize it got pushed to my github.

**Pull request closed without merging**
